TabRanks:
  Admin: "&8[&cAdministrator&8] &c"
  HeadArchitekt: 
  Developer: 
  Owner: 
  Builder: 
  Architekt: 
  Artisan: 
  Gameadmin: 
  Moderator: 
  TestSupporter: 
  Legende: 
  YouTuber: 
  HeadModerator: 
  Member: 
  Serverinhaber:
  Titan: 
  Test-Developer: 
  Supporter: 
